services:
  charzweb:
    build: .
    container_name: charzweb-dev
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    networks:
      - charznet

networks:
  charznet:
    driver: bridge

